security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\IdUser
                property: email  # Assurez-vous que c'est bien "email"

    firewalls:
        main:
            custom_authenticators:
                - App\Security\GoogleAuthenticator
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: front_login
                check_path: front_login
                username_parameter: email  # Remplace "username" par "email"
                password_parameter: password
                default_target_path: app_avis_new
            logout:
                path: front_logout
                target: front_login

    access_control:
        #- { path: ^/ajouter-user, roles: ROLE_ADMIN }
        #- { path: ^/ajouter-user, roles: ROLE_PROFESSIONNEL }
        #- { path: ^/patient-dashboard, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
